export const NOREQUESTBODY = "No request data provided";
export const ZODERROR = "Zod errors";
export const UNIQUEUSERNAMECONSTRAINTVIOLATION = "The username is already in use";
export const UNIQUEEMAILCONSTRAINTVIOLATION = "The email is already in use";
export const ISSUEWITHDATABASE = "Issue talking to the database";
export const SUCCESSFULUSERCREATED = "User created successfully now verify the user"
export const USERNOTFOUND = "User not found in the database"
export const INVALIDOTP = "Invalid OTP provided, recheck or request new OTP"
export const VERIFIEDUSER = "Successfully verified the user, now you can login"
export const USERNOTVERIFIED = "User has not been verified yet"
export const PASSWORDINVALID = "Incorrect password, try to login again"
export const SUCCESSFULLYLOGGEDIN = "User successfully logged in"
export const UNAUTHORIZED = "Forbidden request! Re-login"
export const LOGGEDOUT = "Logged out successfully"
export const PASSWORDUPDATEDSUCCESSFULLY = "Password updated successfully"
